version: '3.3'

services:
    node:
        build:
            context: ./node
        volumes:
            - ../api/:/opt/api
        restart: always
        ports:
            - "8080:8080"
        links:
            - mongo
        tty: true
    mongo:
        build: ./mongo
        expose:
            - "27017"
        volumes:
            - ./data/mongo:/var/lib/mongodb
    nginx:
        build:
            context: ./nginx
        volumes:
            - ./data/logs/nginx:/var/log/nginx
        ports:
            - "80:80"
            - "443:443"
        tty: true
